# Generated by Django 2.0.12 on 2019-10-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='所在部门'),
        ),
        migrations.AlterField(
            model_name='user',
            name='globetrotters',
            field=models.CharField(blank=True, choices=[('有', '有'), ('无', '无')], default='无', max_length=32, null=True, verbose_name='海外经历'),
        ),
        migrations.AlterField(
            model_name='user',
            name='household_register_city',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='户口所在（市）'),
        ),
        migrations.AlterField(
            model_name='user',
            name='household_register_province',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='户口所在（省）'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.CharField(default='', max_length=18, verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='live_city',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='现居城市（市）'),
        ),
        migrations.AlterField(
            model_name='user',
            name='live_district',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='现居城市（县）'),
        ),
        migrations.AlterField(
            model_name='user',
            name='live_province',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='现居城市（省）'),
        ),
        migrations.AlterField(
            model_name='user',
            name='marriage_status',
            field=models.CharField(blank=True, choices=[('未婚', '未婚'), ('已婚', '已婚'), ('离异', '离异')], default='未婚', max_length=32, null=True, verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='user',
            name='politics',
            field=models.CharField(blank=True, choices=[('群众', '群众'), ('团员', '团员'), ('中共党员(含预备党员)', '中共党员(含预备党员)'), ('民主党派', '民主党派'), ('无党派人士', '无党派人士')], default='群众', max_length=32, null=True, verbose_name='政治面貌'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_unit',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='工作单位'),
        ),
    ]
