# Generated by Django 2.0.12 on 2019-10-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191030_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalcertificationorqualification',
            name='extra',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='额外的资料'),
        ),
        migrations.AlterField(
            model_name='professionalcertificationorqualification',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='专业认证或资质'),
        ),
        migrations.AlterField(
            model_name='professionalcertificationorqualification',
            name='obtain_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='获取时间'),
        ),
    ]
