# Generated by Django 2.0.12 on 2019-10-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191031_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologicalinnovation',
            name='extra',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='额外的资料'),
        ),
        migrations.AlterField(
            model_name='technologicalinnovation',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='科技创新'),
        ),
        migrations.AlterField(
            model_name='technologicalinnovation',
            name='obtain_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='获取时间'),
        ),
    ]
