# Generated by Django 2.0.12 on 2019-10-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191031_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honour',
            name='extra',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='额外的资料'),
        ),
        migrations.AlterField(
            model_name='honour',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='荣誉奖章'),
        ),
        migrations.AlterField(
            model_name='honour',
            name='obtain_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='获取时间'),
        ),
        migrations.AlterField(
            model_name='skillscompetition',
            name='extra',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='额外的资料'),
        ),
        migrations.AlterField(
            model_name='skillscompetition',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='技能竞赛'),
        ),
        migrations.AlterField(
            model_name='skillscompetition',
            name='obtain_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='获取时间'),
        ),
    ]
