# Generated by Django 2.0.12 on 2019-10-31 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191031_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_certification_or_qualification', models.FloatField(default=0, verbose_name='专业认证或资质')),
                ('thesis_works', models.FloatField(default=0, verbose_name='论文著作')),
                ('national_patent', models.FloatField(default=0, verbose_name='国家专利')),
                ('technological_innovation', models.FloatField(default=0, verbose_name='科技创新')),
                ('skills_competition', models.FloatField(default=0, verbose_name='技能竞赛')),
                ('honour', models.FloatField(default=0, verbose_name='荣誉奖章')),
                ('professional', models.FloatField(default=0, verbose_name='职称/职鉴')),
                ('edu', models.FloatField(default=0, verbose_name='教育经历')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='账号')),
            ],
        ),
        migrations.AlterField(
            model_name='edu',
            name='colleges',
            field=models.CharField(default='', max_length=32, verbose_name='院校'),
        ),
        migrations.AlterField(
            model_name='edu',
            name='degree',
            field=models.IntegerField(choices=[(1, '学士学位'), (2, '硕士学位'), (3, '博士学位'), (4, '其他')], default=1, verbose_name='学位'),
        ),
        migrations.AlterField(
            model_name='edu',
            name='education',
            field=models.IntegerField(choices=[(1, '初中'), (2, '中技'), (3, '高中'), (4, '大专'), (5, '本科'), (6, '硕士'), (7, 'MBA'), (8, 'EMBA'), (9, '博士'), (10, '其他')], default=1, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='edu',
            name='graduate_end_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='edu',
            name='graduate_start_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='edu',
            name='major',
            field=models.CharField(default='', max_length=32, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='edu',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='学校名称'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='extra',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='额外的资料'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='职称/职鉴'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='obtain_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='获取时间'),
        ),
    ]
