# Generated by Django 2.0.12 on 2019-10-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191031_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='sum',
            field=models.FloatField(default=0, verbose_name='总成绩'),
        ),
        migrations.AlterField(
            model_name='honour',
            name='level',
            field=models.IntegerField(choices=[(1, '国家级技术能手、五一劳动奖章、劳动模范（先进工作者、标兵)'), (2, '省、部、集团级技术能手、五一劳动奖章、劳动模范（先进工作者、标兵)'), (3, '地、厅、省公司级技术能手、五一劳动奖章、劳动模范（先进工作者、标兵)')], default=1, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='nationalpatent',
            name='level',
            field=models.IntegerField(choices=[(1, '国家发明专利'), (2, '实用行新型专利')], default=1, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='skillscompetition',
            name='level',
            field=models.IntegerField(choices=[(1, '国家级(一等奖)'), (2, '国家级(二等奖)'), (3, '国家级(三等奖)'), (4, '国家级(优秀奖或团体奖)'), (5, '省、部、集团级(一等奖)'), (6, '省、部、集团级(二等奖)'), (7, '省、部、集团级(三等奖)'), (8, '省、部、集团级(优秀奖或团体奖)'), (9, '地、厅、省公司级(一等奖)'), (10, '地、厅、省公司级(二等奖)'), (11, '地、厅、省公司级(三等奖)')], default=1, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='technologicalinnovation',
            name='level',
            field=models.IntegerField(choices=[(1, '国家级(一等奖)'), (2, '国家级(二等奖)'), (3, '国家级(三等奖)'), (4, '省、部、集团级(一等奖)'), (5, '省、部、集团级(二等奖)'), (6, '省、部、集团级(三等奖)'), (7, '地、厅、省公司级(已等奖)'), (8, '地、厅、省公司级(已等奖)'), (9, '地、厅、省公司级(已等奖)')], default=1, verbose_name='等级'),
        ),
    ]
