# Generated by Django 2.0.12 on 2019-11-01 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191031_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '有效'), (0, '无效')], default=1, verbose_name='是否被删除')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MajorSecond', verbose_name='报名的专业')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='账号')),
            ],
        ),
    ]
