# Generated by Django 2.0.12 on 2019-11-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.CharField(blank=True, default='/upload/common/portrait.jpg', max_length=300, null=True, verbose_name='头像'),
        ),
    ]
